name: Prebuild and push container to GHCR
# based on https://github.com/devcontainers/ci/blob/main/docs/github-action.md
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 21 * * *' # build latest image at 21:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          imageName: ghcr.io/${{ github.repository }}
          cacheFrom: ghcr.io/${{ github.repository }}
          # Only push image on schedule or push to main branch
          push: filter
          refFilterForPush: "refs/heads/main"
          eventFilterForPush: push, schedule